" Auto-install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

set ttyfast
set t_ut=
"set term=xterm-256color
"set background=light
set clipboard=unnamedplus

if has('termguicolors')
    set termguicolors
endif

call plug#begin(data_dir . '/plugins')
    source ~/.dotfiles/vim/plugins/colorschemes.vim
    source ~/.dotfiles/vim/plugins/commentary.vim
    source ~/.dotfiles/vim/plugins/nerdtree.vim
    source ~/.dotfiles/vim/plugins/gitgutter.vim
    source ~/.dotfiles/vim/plugins/coc.vim
    source ~/.dotfiles/vim/plugins/fzf.vim
    source ~/.dotfiles/vim/plugins/polyglot.vim
    source ~/.dotfiles/vim/plugins/editor-config.vim
    source ~/.dotfiles/vim/plugins/vim-test.vim
    source ~/.dotfiles/vim/plugins/surround.vim
    "source ~/.dotfiles/vim/plugins/vim-wiki.vim
call plug#end()

doautocmd User PlugLoaded

set directory=~/.vim/tmp//

set hidden

set expandtab
set shiftwidth=4
set tabstop=4
set number
set list
set listchars=tab:▸\ ,trail:·
set spell

map gf :edit <cfile><cr>

nmap <leader>ve :edit ~/.dotfiles/vim/vimrc<cr>
nmap <leader>vr :source ~/.dotfiles/vim/vimrc<cr>
nmap <leader>vs :set spell!<cr>
nmap <leader>vl :set list!<cr>

set mouse=a
