set nocompatible
filetype off
syntax on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

	Plugin 'sheerun/vim-polyglot'
"	Plugin 'vim-utils/vim-ruby-fold'
	

	Plugin 'scrooloose/nerdtree'
	Plugin 'majutsushi/tagbar'
	Plugin 'bling/vim-airline'
	Plugin 'nathanaelkane/vim-indent-guides'

	Plugin 'kien/ctrlp.vim'

	Plugin 'terryma/vim-expand-region'
	Plugin 'terryma/vim-multiple-cursors'

	Plugin 'Xuyuanp/nerdtree-git-plugin'
	Plugin 'tpope/vim-fugitive'
	Plugin 'airblade/vim-gitgutter'

	Plugin 'msanders/snipmate.vim'

	Plugin 'vimwiki/vimwiki'
	Plugin 'plasticboy/vim-markdown'

	Plugin 'ciaranm/detectindent'

	Plugin 'ap/vim-css-color'

	Plugin 'junegunn/seoul256.vim'
"	Plugin 'flazz/vim-colorschemes'
	Plugin 'ajh17/Spacegray.vim'
	Plugin 'bluz71/vim-moonfly-colors'
	Plugin 'ajmwagar/vim-dues'


"	Plugin 'scrooloose/syntastic'
" Plugin 'derekwyatt/vim-scala'
" Plugin 'vim-ruby/vim-ruby'


" Plugin 'editorconfig/editorconfig-vim'
" Plugin 'Valloric/YouCompleteMe'

call vundle#end() 

let g:gitgutter_realtime = 0
let g:gitgutter_eager = 0

map K <Plug>(expand_region_expand)
map J <Plug>(expand_region_shrink)



color seoul256
set background=dark
let g:solarized_termcolors=256



" Sane default indentation filetype plugin indent on
set tabstop=4
set softtabstop=4
set shiftwidth=4

" autocmd BufEnter *.{py,php} highlight OverLength ctermbg=darkgrey guibg=#592929
" autocmd BufEnter *.{py,php} match OverLength /\%79v.*/

autocmd BufEnter *.rb set ai tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd BufEnter *.rake set ai tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufEnter *.sh set ai tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufEnter *.json set ai tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufEnter *.js set ai tabstop=2 softtabstop=2 shiftwidth=2
autocmd BufEnter *.yml set ai tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd BufEnter *.yaml set ai tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd BufEnter *.py set ai sw=4 ts=4

set laststatus=2

au FileType haskell,vhdl,ada,sql let b:comment_leader = '-- '
au FileType vim let b:comment_leader = '" '
au FileType c,cpp,java,php,javascript let b:comment_leader = '// '
au FileType sh,make,python let b:comment_leader = '# '
au FileType tex let b:comment_leader = '% '



" ,c and ,u will toggle line comments
noremap <silent> ,c :<C-B>sil <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:noh<CR>
noremap <silent> ,u :<C-B>sil <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:noh<CR>


" Toggle NerdTREE
map <F9> :NERDTreeToggle <CR>
nmap <F8> :TagbarToggle<CR>

set number

"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" let g:syntastic_auto_loc_list = 1

let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '!'

let g:multi_cursor_exit_from_insert_mode = 0

xmap m     <Plug>(expand_region_expand)
xmap <m-m> <Plug>(expand_region_shrink)

set lazyredraw
set cursorline

set t_Co=256


set hlsearch

highlight ColorColumn ctermbg=8
set colorcolumn=80



" These might break outside of my own runtime
let g:airline_powerline_fonts = 1
set term=screen-256color
set directory=~/.vim/tmp
set ttyfast
set hidden

set list listchars=trail:·,precedes:«,extends:»,tab:·\ 
set clipboard+=unnamed



" unicode symbols
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
"let g:airline_symbols.linenr = '␊'
"let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
"let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'





let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.maxlinenr = '☰'
let g:airline_symbols.maxlinenr = ''
"let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'


" Wiki config
let g:vimwiki_list = [{'path': '~/.vim/wiki/', 'syntax': 'markdown', 'ext': '.md'}]
