plugins: bpd discogs chroma ftintitle missing fetchart importadded info types edit smartplaylist fuzzy beatport
import:
    move: yes
    write: yes

directory: ~/Music-Beets
library: ~/.config/beets/library.db
chroma:
    auto: no

types:
    rating: int

smartplaylist:
    relative_to: beets:/
    playlist_dir: /var/lib/mopidy/local/playlists/
    playlists:
        - name: funk.m3u
          query: funk

        - name: recently-added.m3u
          query: added:2016-05-15.. added-
