plugins: bpd ftintitle duplicates missing fetchart importadded info types edit smartplaylist fuzzy scrub inline unimported
import:
  #move: yes
  write: yes
  set_fields:
    grouping: uncategorised

format_item: "$added: $grouping/$albumtype: $albumartist/$artist - ($original_year - $disc/$disctotal) $album - ($track/$tracktotal) $title ($bitrate)"

directory: ~/Music/beets/
library: ~/.local/share/beets/library.db
chroma:
  auto: no

original_year: yes

types:
  rating: int

paths:
  default: "$grouping/$albumartist/$album%aunique{}/$track $title"
  comp: "$grouping/Compilations/$album%aunique{}/$track $title"

unimported:
  ignore_extensions: jpg png

smartplaylist:
  relative_to: /home/leprechaun/Music/
  urlencode: yes
  playlist_dir: ~/.local/share/mopidy/m3u/
  prefix: "local:track:"
  playlists:
    - name: funk-60s.m3u
      query:
        - "funk year:1960..1969"
    - name: funk-70s.m3u
      query:
        - "funk year:1970..1979"
    - name: funk-80s.m3u
      query:
        - "funk year:1980..1989"
    - name: funk-90s.m3u
      query:
        - "funk year:1990..1999"
    - name: funk-00s.m3u
      query:
        - "funk year:2000..2090"
    - name: funk-10s.m3u
      query:
        - "funk year:2010..2019"

    - name: hiphop-80s.m3u
      query:
        - "hiphop year:1980..1989"
    - name: hiphop-90s.m3u
      query:
        - "hiphop year:1990..1999"
    - name: hiphop-00s.m3u
      query:
        - "hiphop year:2000..2090"
    - name: hiphop-10s.m3u
      query:
        - "hiphop year:2010..2019"

    - name: jazz.m3u
      query:
        - "jazz"

    - name: sampled.m3u
      query:
        - samplee
    - name: samplee.m3u
      query:
        - sampled

    - name: recently-added.m3u
      query: added:2022-12-29..

    - name: low-bitrate.m3u
      query: bitrate:..128000

    - name: high-bitrate.m3u
      query: bitrate:220000..
