plugins: web bpd discogs chroma ftintitle missing fetchart importadded info types edit smartplaylist
import:
    move: yes
    write: yes

directory: ~/Music-Beets
library: ~/.config/beets/library.db
chroma:
    auto: no

types:
    rating: int

smartplaylist:
    relative_to: /home/leprechaun/Music-Beets/
    playlist_dir: ~/.config/beets/playlists/
    playlists:
        - name: funk.m3u
          query: funk

        - name: recently-added.m3u
          query: added:2016-05-15.. added-
